/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCService_CONSTANTS_H
#define RPCService_CONSTANTS_H

#include "RPCService_types.h"

namespace powermax { namespace rpc {

class RPCServiceConstants {
 public:
  RPCServiceConstants();

};

extern const RPCServiceConstants g_RPCService_constants;

}} // namespace

#endif
