/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RPCService_constants.h"

namespace powermax { namespace rpc {

const RPCServiceConstants g_RPCService_constants;

RPCServiceConstants::RPCServiceConstants() {
}

}} // namespace

