// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RpcService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::powermax::rpc;

class RpcServiceHandler : virtual public RpcServiceIf {
 public:
  RpcServiceHandler() {
    // Your initialization goes here
  }

  void ping(SimpleReturn& _return) {
    // Your implementation goes here
    printf("ping\n");
  }

  void sendDoubleData(SimpleReturn& _return, const std::vector<DoubleValue> & doubleValue) {
    // Your implementation goes here
    printf("sendDoubleData\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<RpcServiceHandler> handler(new RpcServiceHandler());
  shared_ptr<TProcessor> processor(new RpcServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

